# Generated by Django 3.1 on 2020-02-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('status', models.BooleanField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('entryFee', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('guysAllowed', models.BooleanField()),
            ],
        ),
    ]
